### ISSUE TITLE
Update due to the new semantic highlighting setting 

### ISSUE THREAD

**Issue by MohamadKh75** [emroussel/atomize#10]
Hey

As you can see in [this issue](https://github.com/microsoft/vscode/issues/92308), there is a new `semanticHighlighting` which breaks the theme and they asked theme maintainers to update the theme.

[changelog](https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting)

**Comment by emroussel** [comment]
@MohamadKh75 thanks for letting me know about this. From looking a bit into the new semantic highlighting system, it uses the same selectors for different types of elements that previously had different colors with this theme. Not sure if there's a solution and what it'll look like, but I'll investigate more very soon.

In the mean time, I would recommend adding this custom setting to disable semantic highlighting

```json
"editor.semanticHighlighting.enabled": false
```

**Comment by mattacosta** [comment]
To literally [quote](https://github.com/microsoft/vscode/issues/92308#issuecomment-597899153) the VSCode team:

> Themes don't need to be updated for semantic highlighting. See here for [more background information for theme authors.](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#as-a-theme-author-do-i-need-to-change-my-theme-to-make-it-work-with-semantic-highlighting)

**Comment by emroussel** [comment]
Yeah it seems like there are no actions that need to be taken for this theme. The syntax is still highlighted correctly based on the types that VS Code gives us.

I added a note to the README to turn off semantic highlighting if people want to have the same syntax highlighting as Atom One Dark, but can't do much more than that.

Feel free to open a new issue or PR if you see problems with semantic highlighting in this theme that can be fixed.

**Comment by MohamadKh75** [comment]
Yep, i turned it off but just want to let you know 😁
