### ISSUE TITLE
selectionHighlight does not work

### ISSUE THREAD

**Issue by bielej** [emroussel/atomize#14]
Hi, 
Your theme breaks highlighting words similar to the selected word.
Despite setting:
```
  // Controls whether the editor should highlight matches similar to the selection.
  "editor.selectionHighlight": true,
```
the editor won't highlight any matching words. 
On other themes (ie. Dark+) selectionHighlight works fine.

**Comment by emroussel** [comment]
@bielej thanks for spotting this! Just merged a PR to add the colors for selection highlighting and will release it later today

**Comment by bielej** [comment]
Thanks - now it's working.
