### ISSUE TITLE
Number sign (#) not highlighted in C++

### ISSUE THREAD

**Issue by Shatur95** [emroussel/atomize#16]
Hi! Thank you for the awesome theme.
Could you highlight `#` sign in `include`? Currently it looks like this:
![изображение](https://user-images.githubusercontent.com/22453358/89097447-ae18fa00-d3e7-11ea-9f74-2a5d98eef764.png)
Usually it looks like this:
![изображение](https://user-images.githubusercontent.com/22453358/89097442-9e011a80-d3e7-11ea-8fc2-4925d1778d7a.png)
The same issue with `define`, `pragma` and other directives.

**Comment by Shatur95** [comment]
Thanks!

**Comment by emroussel** [comment]
@Shatur95 no problem, thanks for reporting this! I just published 1.5.1 with this fix, it should be available in a couple of minutes.

I don't use C++, so don't hesitate to let me know if there are any other discrepancies/weird colors with this theme!

**Comment by Shatur95** [comment]
Tested, works as expected now :)
