### ISSUE TITLE
Suggestion about C++ namespace highlighting

### ISSUE THREAD

**Issue by Shatur95** [emroussel/atomize#18]
Currently, namespaces in C ++ are highlighted as variables. But usually it highlighted as **types** in C++ IDE's. Could you change it?

Current:

![изображение](https://user-images.githubusercontent.com/22453358/90332464-c5e6a580-dfc5-11ea-822f-04bc511234f2.png)

Expected (QtCreator):

![изображение](https://user-images.githubusercontent.com/22453358/90332478-ef073600-dfc5-11ea-84fa-cfaef5ad8b44.png)

[File from screenshot](https://github.com/Shatur95/akd/blob/master/src/layout.cpp).

**Comment by Shatur95** [comment]
Accidentally hit enter before writing the description. Updated.

So, my suggestion is highlight namespaces in yellow color.

**Comment by emroussel** [comment]
@Shatur95 thanks for the suggestion, I think that makes sense. Do you mind opening a PR to make the change? It can probably be similar to the last C++ change I made after you find the right scope for those types:
https://github.com/emroussel/atomize/blob/master/themes/Atomize-color-theme.json#L877-L886

**Comment by Shatur95** [comment]
Thanks, I think I know how to do it, will send a PR in this week.
