### ISSUE TITLE
es6 template string

### ISSUE THREAD

**Issue by la-magbanua** [emroussel/atomize#20]
Change colors for the dollar sign and the curly brackets in a template string. Makes scanning with the eyes much easier.

![image](https://user-images.githubusercontent.com/56512548/95548952-c6854080-0a38-11eb-937e-b517e3bfc668.png)

**Comment by emroussel** [comment]
Hey @la-magbanua, can you elaborate on this? What color do you think it should be and why? The goal of this theme is to follow most of the colors from Atom One Dark, so this is why they're currently green like the rest of the string. I personally don't see a reason to change it, but am open to hearing what you have to say.

**Comment by la-magbanua** [comment]
I think making it color red would be just fine so that it would pop out just a bit when making queries in fetch or useEffect but I totally see where you're coming from and now I understand the reason as to why the colors are like that. Thanks!

**Comment by emroussel** [comment]
Makes sense. Thanks for the suggestion, but I will leave it as is since that's what Atom does and I personally like it better that way (makes it easier to read the variable name in my opinion)
