### ISSUE TITLE
Is there a way to add a color for the Remote Settings in the Status Bar? 

### ISSUE THREAD

**Issue by LittleHoopoe** [emroussel/atomize#25]
First of all I love your theme! It's one of my favorite. I googled and search how to change this color: 
![image](https://user-images.githubusercontent.com/713681/143561063-890fe572-fb81-44c7-8419-097d1e9b4707.png)

But no Luck at all :( Is there a way to change this by adding something to the settings.json? 

Best Regards

**Comment by emroussel** [comment]
@LittleHoopoe thanks for the kind words. You can edit colors (no matter the theme) with the `workbench.colorCustomizations` key in `settings.json`. I think the one you're pointing at is the `statusBar.foreground`/`statusBar.background`, but you can look at the VS Code color reference for more info and to see all possible keys to customize: https://code.visualstudio.com/api/references/theme-color

**Comment by LittleHoopoe** [comment]
just leaving it here, maybe someone else is looking for it:
statusBarItem.remoteBackground: Background color for the remote indicator on the status bar.
statusBarItem.remoteForeground: Foreground color for the remote indicator on the status bar.

and just feeling dump that I missed the official documentation for theme-colors -_-

Thank you for fast response and your kindness!
