### ISSUE TITLE
Typescript generic not being parsed correctly

### ISSUE THREAD

**Issue by anisometropie** [emroussel/atomize#28]
I have this function in typescript. the parameters are written on separates lines, and the colors are not correct here for the generic params :
![Screenshot_20230116_115513](https://user-images.githubusercontent.com/24652545/212661846-88374481-80ba-4653-93a0-e6eaa7bfd47e.png)

generic params should appear as yellow, and `extends keyof` as purple.
If I write the parameters on the same line as the generic params I get a correct rendering :

![Screenshot_20230116_115442](https://user-images.githubusercontent.com/24652545/212661743-f971a543-8359-4dc4-906a-83afe4d79824.png)

Vscode 1.74.2
atomize v 2.0.2

**Comment by emroussel** [comment]
This is an issue with the typescript textmate scopes in vscode, not with this theme (the same issue happens on other themes as well). I think it might be a limitation of the [current typescript textmate language](https://github.com/microsoft/TypeScript-TmLanguage) which doesn't allow multi-line lookup, so it might not be fixable (sounds similar to https://github.com/microsoft/TypeScript-TmLanguage/issues/767).
