### ISSUE TITLE
Include an Atom icon-set in this theme or point to one in readme

### ISSUE THREAD

**Issue by touqeerkhan11** [emroussel/atomize#3]
Is there an icon set that resembles the Atom file explorer icons? What did you use in the screenshot because after installing this theme the file explorer icons weren't updated and its really hard to navigate productively with anything else

**Comment by emroussel** [comment]
@touqeerkhan11 I made my own icon theme with the icons used by Atom. Let me see if I can package it and publish it to the marketplace this weekend.

In the mean time, I'd recommend using the `vs-minimal` icon theme. It comes with vs code, and is the code that I found to be the closest to Atom.

**Comment by touqeerkhan11** [comment]
@emroussel Thank you so much if you can do that - file explorer UI makes a huge difference when exploring code you are not familiar with and because you have solved this problem I think you already know :)

**Comment by emroussel** [comment]
@touqeerkhan11 totally!

I published the icon theme here: https://marketplace.visualstudio.com/items?itemName=emroussel.atom-icons

I also added a link to it in the readme of this repo. Definitely feel free to open an issue on the [atom-icons repo](https://github.com/emroussel/atom-icons) if you find that something is missing or incorrect.
