### ISSUE TITLE
editorGroup.border

### ISSUE THREAD

**Issue by perragnar** [emroussel/atomize#4]
I would love to have a border between editor groups.

Current: 
<img width="511" alt="Screenshot 2019-04-10 at 09 42 09" src="https://user-images.githubusercontent.com/1774047/55860731-34ffee80-5b75-11e9-9555-f0eb6174fef5.png">

With `"editorGroup.border": "#181A1F`:
<img width="511" alt="Screenshot 2019-04-10 at 09 42 16" src="https://user-images.githubusercontent.com/1774047/55860732-34ffee80-5b75-11e9-8d44-f33e133f0029.png">

Great theme by the way!

**Comment by emroussel** [comment]
Hey @perragnar! There should already be a border on editor groups: https://github.com/emroussel/atomize/blob/master/themes/Atomize-color-theme.json#L64

Are you using the latest atomize and vs code?

**Comment by perragnar** [comment]
Hey!
Strange.. I had the latest version of VSCode and Atomize but I reinstalled VSCode and now it works. Must have been something with my VSCode.

Cheers!

**Comment by emroussel** [comment]
Glad you figured it out! Don't hesitate to open another issue if you find something else that can be improved
