### ISSUE TITLE
No contrast on Command Palette when all tabs are closed

### ISSUE THREAD

**Issue by thiagomajesk** [emroussel/atomize#7]
Since the background of the Command Palette is the same as the rest of the editor's background, there's no contrast when all tabs are closed. The same does not happen when you have at least one editor open (because of the background difference). See images below...

![image](https://user-images.githubusercontent.com/13930952/73476541-305d2e80-4371-11ea-977b-6fe5e62c7c81.png)

![image](https://user-images.githubusercontent.com/13930952/73476655-6e5a5280-4371-11ea-8eb8-7c201b7a8f57.png)

**Comment by emroussel** [comment]
Hey @thiagomajesk thanks for flagging this! Unfortunately it looks like VS Code doesn't allow us to [set a border on this element](https://code.visualstudio.com/api/references/theme-color#quick-picker), which would help add more contrast. I might experiment a bit with box shadows, I've been wanting to have a border on the quick pick and editor widgets (like search and replace) for a while, but have not found a way to do it.

Either way, making the background of the empty editor the same as when you open a file would solve the issue. I'll do that this weekend.

**Comment by emroussel** [comment]
@thiagomajesk I just published this under 1.4.3 along a couple other small changes

**Comment by thiagomajesk** [comment]
@emroussel Just tested, look very good 👌
